"""Markdown scanning and generated-output writing for Agent Doc Board."""

from __future__ import annotations

from datetime import datetime, timezone
import fnmatch
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
from urllib.parse import unquote, urlparse

from agent_doc_board.config import CategoryRule, ProjectConfig, load_config


GENERATED_NOTE = "<!-- Generated by agent-doc-board; edit .agent-docs/config.toml for categories. -->"


def build_manifest(root: Path) -> dict:
    """Build a deterministic documentation manifest for a project root."""
    root = root.expanduser().resolve()
    config = load_config(root)
    docs = [_doc_record(root, path, config) for path in _iter_markdown_files(root, config)]
    _attach_doc_graph(docs)
    todos = _read_or_seed_todos(root, config)
    data_refs = [_data_ref_record(root, ref) for ref in config.data_refs]

    categories = [
        {
            "id": category.id,
            "title": category.title,
            "description": category.description,
            "count": sum(1 for doc in docs if doc["category"] == category.id),
        }
        for category in config.categories
    ]
    uncategorized_count = sum(1 for doc in docs if doc["category"] == "uncategorized")
    if uncategorized_count:
        categories.append(
            {
                "id": "uncategorized",
                "title": "Uncategorized",
                "description": "Markdown files not matched by a category rule.",
                "count": uncategorized_count,
            }
        )

    return {
        "schema_version": 1,
        "project_root": str(root),
        "docs_root": str(root / "docs"),
        "categories": categories,
        "docs": docs,
        "todos": todos,
        "data_refs": data_refs,
    }


def write_project_outputs(root: Path, manifest: dict) -> None:
    """Write manifest, markdown index, and initial TODO outputs for a project."""
    root = root.expanduser().resolve()
    agent_dir = root / ".agent-docs"
    docs_dir = root / "docs"
    agent_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = agent_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")

    (docs_dir / "INDEX.md").write_text(_render_index(manifest))
    todo_path = docs_dir / "TODO.md"
    if not todo_path.exists():
        todo_path.write_text(_render_todo(manifest))


def _iter_markdown_files(root: Path, config: ProjectConfig) -> list[Path]:
    """Return all included markdown files in deterministic order."""
    candidates: dict[str, Path] = {}
    for pattern in config.include:
        for path in root.glob(pattern):
            if path.is_file() and path.suffix.lower() == ".md":
                rel = path.relative_to(root).as_posix()
                if not _matches_any(rel, config.exclude):
                    candidates[rel] = path
    return [candidates[key] for key in sorted(candidates)]


def _doc_record(root: Path, path: Path, config: ProjectConfig) -> dict:
    """Build one markdown document record for the board manifest."""
    rel = path.relative_to(root).as_posix()
    text = path.read_text(errors="replace")
    title = _extract_title(text) or _title_from_path(path)
    category = _category_for(rel, config.categories)
    summary = _extract_summary(text, title)
    stat = path.stat()
    return {
        "id": hashlib.sha1(rel.encode("utf-8")).hexdigest()[:10],
        "title": title,
        "path": rel,
        "abs_path": str(path.resolve()),
        "category": category,
        "status": _status_for(rel),
        "tags": _tags_for(rel, category),
        "summary": summary,
        "date": _extract_doc_date(rel, text, stat),
        "mtime": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(timespec="seconds"),
        "size_bytes": stat.st_size,
        "outgoing_links": [],
        "backlinks": [],
        "related": [],
        "topic_timeline": [],
        "_raw_links": _extract_markdown_links(text),
    }


def _attach_doc_graph(docs: list[dict]) -> None:
    """Attach backlinks, related docs, and topic timelines to manifest docs."""
    docs_by_path = {doc["path"]: doc for doc in docs}
    for doc in docs:
        outgoing = []
        for raw_target in doc.pop("_raw_links", []):
            normalized = _normalize_doc_link(doc["path"], raw_target, docs_by_path)
            if normalized and normalized != doc["path"] and normalized not in outgoing:
                outgoing.append(normalized)
        doc["outgoing_links"] = [_doc_link_record(docs_by_path[path], "links to") for path in outgoing]

    for doc in docs:
        doc["backlinks"] = []
    for source in docs:
        for target in source["outgoing_links"]:
            target_doc = docs_by_path[target["path"]]
            target_doc["backlinks"].append(_doc_link_record(source, "linked from"))

    for doc in docs:
        doc["related"] = _related_docs_for(doc, docs)
        doc["topic_timeline"] = _topic_timeline_for(doc, docs)


def _extract_markdown_links(text: str) -> list[str]:
    """Extract markdown and wiki-style link targets from a document body."""
    markdown_links = re.findall(r"(?<!!)\[[^\]]+\]\(([^)]+)\)", text)
    wiki_links = re.findall(r"\[\[([^\]]+)\]\]", text)
    return [*markdown_links, *wiki_links]


def _normalize_doc_link(current_rel: str, raw_target: str, docs_by_path: dict[str, dict]) -> str | None:
    """Normalize a markdown link target to a manifest document path when possible."""
    target = unquote(str(raw_target).strip())
    if not target or target.startswith(("#", "http://", "https://", "mailto:")):
        return None
    parsed = urlparse(target)
    target_path = parsed.path
    if not target_path:
        return None
    if target_path.startswith("/"):
        marker = "/docs/"
        if marker in target_path:
            candidate = "docs/" + target_path.split(marker, 1)[1]
        else:
            candidate = target_path.lstrip("/")
    else:
        candidate = PurePosixPath(current_rel).parent.joinpath(target_path).as_posix()
    candidate = PurePosixPath(candidate).as_posix()
    parts = []
    for part in candidate.split("/"):
        if part in ("", "."):
            continue
        if part == "..":
            if parts:
                parts.pop()
            continue
        parts.append(part)
    candidate = "/".join(parts)
    if candidate in docs_by_path:
        return candidate
    if not candidate.endswith(".md") and f"{candidate}.md" in docs_by_path:
        return f"{candidate}.md"
    return None


def _doc_link_record(doc: dict, reason: str) -> dict:
    """Return a compact document reference for graph panels."""
    return {
        "path": doc["path"],
        "title": doc["title"],
        "category": doc["category"],
        "date": doc.get("date", ""),
        "summary": doc.get("summary", ""),
        "reason": reason,
    }


def _related_docs_for(doc: dict, docs: list[dict], limit: int = 8) -> list[dict]:
    """Rank nearby docs by explicit links, shared tags, category, and title terms."""
    outgoing = {item["path"] for item in doc.get("outgoing_links", [])}
    incoming = {item["path"] for item in doc.get("backlinks", [])}
    doc_tags = set(doc.get("tags", []))
    doc_terms = _title_terms(doc["title"])
    related = []
    for other in docs:
        if other["path"] == doc["path"]:
            continue
        reasons = []
        score = 0.0
        if other["path"] in outgoing:
            score += 6
            reasons.append("explicit link")
        if other["path"] in incoming:
            score += 6
            reasons.append("backlink")
        shared_tags = sorted(doc_tags.intersection(other.get("tags", [])))
        if shared_tags:
            score += 2 * len(shared_tags)
            reasons.append("shared tags: " + ", ".join(shared_tags[:3]))
        if other.get("category") == doc.get("category"):
            score += 1
            reasons.append("same category")
        shared_terms = sorted(doc_terms.intersection(_title_terms(other["title"])))
        if shared_terms:
            score += 0.5 * min(len(shared_terms), 4)
            reasons.append("shared title terms")
        if score <= 0:
            continue
        item = _doc_link_record(other, "; ".join(reasons[:3]))
        item["score"] = round(score, 2)
        related.append(item)
    return sorted(related, key=lambda item: (-item["score"], item.get("date", ""), item["path"]))[:limit]


def _topic_timeline_for(doc: dict, docs: list[dict], limit: int = 14) -> list[dict]:
    """Return a chronological timeline for docs sharing this document's topic tags."""
    doc_tags = set(doc.get("tags", []))
    candidates = []
    for other in docs:
        shared_tags = sorted(doc_tags.intersection(other.get("tags", [])))
        same_category = other.get("category") == doc.get("category")
        if not shared_tags and not same_category:
            continue
        item = _doc_link_record(other, "current" if other["path"] == doc["path"] else ", ".join(shared_tags) or "same category")
        item["current"] = other["path"] == doc["path"]
        candidates.append(item)
    return sorted(candidates, key=lambda item: (item.get("date", ""), item["path"]))[-limit:]


def _title_terms(title: str) -> set[str]:
    """Extract coarse title terms for lightweight related-doc ranking."""
    stopwords = {"the", "and", "for", "with", "from", "into", "current", "docs", "plan"}
    return {token for token in re.findall(r"[a-zA-Z0-9]{3,}", title.lower()) if token not in stopwords}


def _extract_doc_date(rel: str, text: str, stat) -> str:
    """Extract a stable document date from filename/body, falling back to mtime."""
    date_match = re.search(r"20\d{2}-\d{2}-\d{2}", rel) or re.search(r"20\d{2}-\d{2}-\d{2}", text[:1200])
    if date_match:
        return date_match.group(0)
    return datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).date().isoformat()


def _data_ref_record(root: Path, ref) -> dict:
    """Build one non-markdown data reference record."""
    abs_path = (root / ref.path).resolve()
    return {
        "title": ref.title,
        "path": ref.path,
        "abs_path": str(abs_path),
        "exists": abs_path.exists(),
        "description": ref.description,
    }


def _extract_title(text: str) -> str | None:
    """Extract the first H1 title from markdown text."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return None


def _extract_summary(text: str, title: str) -> str:
    """Extract a compact summary from the first useful markdown paragraph."""
    lines = text.splitlines()
    in_fence = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or not stripped:
            continue
        if stripped.startswith("#"):
            heading_text = stripped.lstrip("#").strip()
            if heading_text == title:
                continue
            return _clip(heading_text)
        if stripped.startswith(("<!--", "|", "-", "*", ">")):
            continue
        return _clip(stripped)
    return ""


def _clip(text: str, limit: int = 220) -> str:
    """Clip text to a board-friendly single-line summary."""
    clean = re.sub(r"\s+", " ", text).strip()
    if len(clean) <= limit:
        return clean
    return clean[: limit - 1].rstrip() + "..."


def _title_from_path(path: Path) -> str:
    """Create a readable title from a markdown filename."""
    return path.stem.replace("_", " ").replace("-", " ").title()


def _category_for(rel: str, categories: tuple[CategoryRule, ...]) -> str:
    """Return the category with the most specific matching pattern."""
    best_category = "uncategorized"
    best_score = -1
    for category in categories:
        score = _best_pattern_score(rel, category.patterns)
        if score > best_score:
            best_category = category.id
            best_score = score
    return best_category


def _matches_any(rel: str, patterns: tuple[str, ...]) -> bool:
    """Check whether a POSIX relative path matches any glob pattern."""
    return any(fnmatch.fnmatchcase(rel, pattern) for pattern in patterns)


def _best_pattern_score(rel: str, patterns: tuple[str, ...]) -> int:
    """Return the literal-character score of the best matching pattern."""
    scores = [
        len(pattern.replace("*", "").replace("?", "").replace("[", "").replace("]", ""))
        for pattern in patterns
        if fnmatch.fnmatchcase(rel, pattern)
    ]
    return max(scores, default=-1)


def _status_for(rel: str) -> str:
    """Infer a lightweight document status from its path."""
    lowered = rel.lower()
    if "archive" in lowered or "old" in lowered:
        return "archive"
    if lowered.endswith("index.md") or lowered.endswith("todo.md"):
        return "generated"
    return "active"


def _tags_for(rel: str, category: str) -> list[str]:
    """Create stable tags from path and category hints."""
    tags = [category]
    lowered = rel.lower()
    for token in ("topic", "plan", "paper", "result", "metric", "experiment", "dataset", "eval", "training", "analysis"):
        if token in lowered:
            tags.append(token)
    return sorted(set(tags))


def _read_or_seed_todos(root: Path, config: ProjectConfig) -> list[dict]:
    """Read TODO entries from docs/TODO.md or seed them from config."""
    todo_path = root / "docs" / "TODO.md"
    if todo_path.exists():
        return _parse_todo_markdown(todo_path.read_text(errors="replace"))
    return [
        {
            "id": f"todo-{index + 1:03d}",
            "priority": todo.priority,
            "status": todo.status,
            "title": todo.title,
            "links": list(todo.links),
            "children": [],
        }
        for index, todo in enumerate(config.todos)
    ]


def _parse_todo_markdown(text: str) -> list[dict]:
    """Parse markdown checkbox TODO entries with optional indented subtasks."""
    todos: list[dict] = []
    parent_pattern = re.compile(r"^- \[(?P<done>[ xX])\]\s+\((?P<priority>P\d)\)\s+(?P<title>.+)$")
    child_pattern = re.compile(r"^\s{2,}- \[(?P<done>[ xX])\]\s+(?P<title>.+)$")
    for line in text.splitlines():
        parent_match = parent_pattern.match(line.strip())
        if parent_match:
            title, links = _parse_todo_title(parent_match.group("title").strip())
            todos.append(
                {
                    "id": f"todo-{len(todos) + 1:03d}",
                    "priority": parent_match.group("priority"),
                    "status": "done" if parent_match.group("done").lower() == "x" else "todo",
                    "title": title,
                    "links": links,
                    "children": [],
                }
            )
            continue
        child_match = child_pattern.match(line)
        if child_match and todos:
            title, links = _parse_todo_title(child_match.group("title").strip())
            todos[-1]["children"].append(
                {
                    "id": f"{todos[-1]['id']}-sub-{len(todos[-1]['children']) + 1:02d}",
                    "status": "done" if child_match.group("done").lower() == "x" else "todo",
                    "title": title,
                    "links": links,
                }
            )
    return todos


def _parse_todo_title(raw_title: str) -> tuple[str, list[str]]:
    """Return a TODO title with markdown links removed plus copied link targets."""
    links = re.findall(r"\[[^\]]+\]\(([^)]+)\)", raw_title)
    title = re.sub(r"\s*\[[^\]]+\]\([^)]+\)", "", raw_title).strip()
    return title, links


def _render_index(manifest: dict) -> str:
    """Render the markdown documentation index."""
    docs_by_category: dict[str, list[dict]] = {}
    for doc in manifest["docs"]:
        docs_by_category.setdefault(doc["category"], []).append(doc)

    category_titles = {category["id"]: category["title"] for category in manifest["categories"]}
    lines = [
        GENERATED_NOTE,
        "# Documentation Index",
        "",
        f"Project root: `{manifest['project_root']}`",
        "",
        "## Categories",
        "",
    ]
    for category in manifest["categories"]:
        lines.append(f"- **{category['title']}** (`{category['id']}`): {category['count']} docs")
    lines.append("")

    for category_id in [category["id"] for category in manifest["categories"]]:
        docs = docs_by_category.get(category_id, [])
        if not docs:
            continue
        lines.extend([f"## {category_titles.get(category_id, category_id)}", ""])
        lines.append("| Document | Status | Tags | Summary |")
        lines.append("| --- | --- | --- | --- |")
        for doc in docs:
            tags = ", ".join(f"`{tag}`" for tag in doc["tags"])
            summary = doc["summary"].replace("|", "\\|")
            lines.append(f"| [{doc['title']}]({doc['path']}) | `{doc['status']}` | {tags} | {summary} |")
        lines.append("")

    if manifest.get("data_refs"):
        lines.extend(["## Data References", ""])
        for ref in manifest["data_refs"]:
            exists = "exists" if ref["exists"] else "missing"
            lines.append(f"- `{ref['path']}` ({exists}): {ref['description']}")
        lines.append("")

    lines.extend(
        [
            "## Local Board",
            "",
            "Run:",
            "",
            "```bash",
            f"agent-doc-board serve --root {manifest['project_root']} --port 8765",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _render_todo(manifest: dict) -> str:
    """Render the initial project TODO markdown file."""
    lines = [
        "# Project TODO",
        "",
        "This file is maintained for agent/project coordination. Keep entries short and link to source docs or external settings when useful.",
        "",
    ]
    for todo in manifest["todos"]:
        links = " ".join(f"[link]({link})" for link in todo["links"])
        suffix = f" {links}" if links else ""
        checkbox = "x" if todo["status"] == "done" else " "
        lines.append(f"- [{checkbox}] ({todo['priority']}) {todo['title']}{suffix}")
        for child in todo.get("children", []):
            child_checkbox = "x" if child["status"] == "done" else " "
            child_links = " ".join(f"[link]({link})" for link in child.get("links", []))
            child_suffix = f" {child_links}" if child_links else ""
            lines.append(f"  - [{child_checkbox}] {child['title']}{child_suffix}")
    lines.append("")
    return "\n".join(lines)
